#!/usr/bin/python

import argparse
import uuid

parser = argparse.ArgumentParser(description='generate Metadata.xml')
group = parser.add_mutually_exclusive_group()
group.add_argument("-ios", action='store_true', default=False)
group.add_argument("-android", action='store_true', default=False)
group.add_argument("-wp", action='store_true', default=False)
group.add_argument("-mac", action='store_true', default=False)

args = parser.parse_args()
platform = None
if args.ios:
	platform = "ios"
elif args.android:
	platform = "android"
elif args.wp:
	platform = "wp"
elif args.mac:
	platform = "mac"

# additional tags per platform
platform_tags = {"ios": ["iOS8"],
		"android": [],
		"wp": [],
		"mac": ["Yosemite"]
}
common_tags = ["User Interface", "Data", "Graphics", "Media", "Platform Features", "Device Features", "Cloud",
			   "Backgrounding", "Maps & Location", "Binding + Interop", "Notifications", "Touch", "Getting Started",
			   "Async"]
platforms = {"ios": "iOS", "android": "Android", "wp": "Windows", "mac": ""}

content_template = """
<?xml version="1.0" encoding="utf-8" ?>
<SampleMetadata>
	<ID>{guid}</ID>
	<IsFullApplication>true|false</IsFullApplication>
	<Level>Advanced|Beginning|Intermediate</Level>
	<Tags>{tags}</Tags>
	<SupportedPlatforms>{platform}</SupportedPlatforms>
	<Gallery>false|true</Gallery>
	<MinimumLicenseRequirement>Starter|Indie|Business|Enterprise</MinimumLicenseRequirement>
</SampleMetadata>
"""
all_tags = []
all_tags.extend(platform_tags[platform])
all_tags.extend(common_tags)
tags = ", ".join(all_tags)

content = content_template.format(guid=str(uuid.uuid1()), tags=tags, platform=platforms[platform])
content = content.strip()
print content