#!/usr/bin/python

import sys
# the path to the file that holds the commit message
print(len(sys.argv))
msg_file_path = sys.argv[1]
commit_type = sys.argv[2]
sha = sys.argv[3] if len(sys.argv) > 3 else None

print 'Number of arguments:', len(sys.argv), 'arguments.'
print 'Argument List:', [msg_file_path, commit_type, sha]