#!/usr/bin/python

import sys
import os
import git

path = os.getcwd()
repo = git.Repo(path)
print(path, repo)

def prepare_commit_msg(msg_file_path):
	with open(msg_file_path, 'r+') as f:
		content = f.read()
		f.seek(0)
		f.write("{0}{1}".format("hello", content))
		f.truncate()

# the path to the file that holds the commit message
arg_len = len(sys.argv)
print(arg_len)
print(sys.argv)
msg_file_path = sys.argv[1]
commit_type = sys.argv[2] if arg_len > 2 else None
sha = sys.argv[3] if arg_len > 3 else None

print 'Number of arguments:', len(sys.argv), 'arguments.'
print 'Argument List:', [msg_file_path, commit_type, sha]

prepare_commit_msg(msg_file_path)